In [1]:
import sys 
sys.path.append(rf"/nfs/home/genovese/thesis-wildfire-genovese/src")
from importlib import reload
import utils
reload(utils)
from utils import *

sys.path.append(rf"/nfs/home/genovese/thesis-wildfire-genovese/src/OnFireForest")
import PointDataLoader
reload(PointDataLoader)
from PointDataLoader import PointDataLoader

In [2]:
ignitions = gpd.read_file('/nfs/home/genovese/thesis-wildfire-genovese/data/nicola/piedmont_2012_2024_fa.geojson').to_crs(epsg=3857)
gdf = separate_date(ignitions, 'initialdate')
row = gdf.iloc[[1206], :]

In [3]:
test = PointDataLoader()
test.set_coordinates(anno = row.YYYY.iloc[0], mese=row.MM.iloc[0], giorno=row.DD.iloc[0], x=row.point_x.iloc[0], y=row.point_y.iloc[0], crs=row.crs)
test.get_coordinates()

{'anno': 2023,
 'mese': 4,
 'giorno': 4,
 'coordinate': <POINT (856763.136 5686588.315)>}

In [26]:
test.load()
table = test.get_table()

AttributeError: 'GeoDataFrame' object has no attribute 'day'

In [ ]:
table.describe()

,analfabeti,alfabeti privi di titolo di studio,licenza di scuola elementare,licenza di scuola media inferiore o di avviamento professionale,diploma di istruzione secondaria di II grado o di qualifica professionale (corso di 3-4 anni) compresi IFTS,diploma di tecnico superiore ITS o titolo di studio terziario di primo livello,titolo di studio terziario di secondo livello e dottorato di ricerca,titolo di studio terziario di secondo livello,dottorato di ricerca/diploma accademico di formazione alla ricerca,totale_istruzione,...,settore_prevalente,tempo_permanenza,durata_calma,umedia,umin,umax,rtot,hdd_base18,hdd_base20,cdd_base18
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN